-- MySQL Script generated by MySQL Workbench
-- Thu Nov 16 21:14:51 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema prototipos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema prototipos
-- -----------------------------------------------------
-- CREATE DATABASE IF NOT EXISTS `prototipos` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ;
-- USE `prototipos` ;

-- -----------------------------------------------------
-- Table `grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo` (
  `idgrupo` INT NOT NULL AUTO_INCREMENT,
  `grado` VARCHAR(1) NOT NULL,
  `letra` VARCHAR(1) NOT NULL,
  `turno` TINYINT NOT NULL,
  `especialidad` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idgrupo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alumnos` (
  `idalumnos` INT NOT NULL AUTO_INCREMENT,
  `no_control` VARCHAR(14) NOT NULL,
  `curp` VARCHAR(18) NOT NULL,
  `grupo_idgrupo` INT NOT NULL,
  PRIMARY KEY (`idalumnos`, `no_control`, `curp`, `grupo_idgrupo`),
  INDEX `fk_alumnos_grupo_idx` (`grupo_idgrupo`),
  CONSTRAINT `fk_alumnos_grupo`
    FOREIGN KEY (`grupo_idgrupo`)
    REFERENCES `grupo` (`idgrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modulos` (
  `idmodulos` INT NOT NULL AUTO_INCREMENT,
  `uac` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(300) NOT NULL,
  `horas` INT NOT NULL,
  `semestre` INT NOT NULL,
  `grupo_idgrupo_m` INT NOT NULL,
  `grupo_idgrupo_v` INT NOT NULL,
  PRIMARY KEY (`idmodulos`, `uac`, `grupo_idgrupo_m`, `grupo_idgrupo_v`),
  INDEX `fk_modulos_grupo1_idx` (`grupo_idgrupo_m`),
  INDEX `fk_modulos_grupo2_idx` (`grupo_idgrupo_v`),
  CONSTRAINT `fk_modulos_grupo1`
    FOREIGN KEY (`grupo_idgrupo_m`)
    REFERENCES `grupo` (`idgrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_modulos_grupo2`
    FOREIGN KEY (`grupo_idgrupo_v`)
    REFERENCES `grupo` (`idgrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `submodulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `submodulos` (
  `idsubmodulos` INT NOT NULL AUTO_INCREMENT,
  `uac` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(300) NOT NULL,
  `horas` INT NOT NULL,
  `modulos_idmodulos` INT NOT NULL,
  PRIMARY KEY (`idsubmodulos`, `modulos_idmodulos`),
  INDEX `fk_submodulos_modulos1_idx` (`modulos_idmodulos`),
  CONSTRAINT `fk_submodulos_modulos1`
    FOREIGN KEY (`modulos_idmodulos`)
    REFERENCES `modulos` (`idmodulos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `materias` (
  `idmaterias` INT NOT NULL AUTO_INCREMENT,
  `uac` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `horas` INT NOT NULL,
  `semestre` INT NOT NULL,
  PRIMARY KEY (`idmaterias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evaluacion_tc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evaluacion_tc` (
  `idevaluacion_tc` INT NOT NULL AUTO_INCREMENT,
  `parcial1` DECIMAL(2,2) NULL,
  `parcial2` DECIMAL(2,2) NULL,
  `parcial3` DECIMAL(2,2) NULL,
  `asistencia1` INT NULL,
  `asistencia2` INT NULL,
  `asistencia3` INT NULL,
  `materias_idmaterias` INT NOT NULL,
  `alumnos_idalumnos` INT NOT NULL,
  PRIMARY KEY (`idevaluacion_tc`, `materias_idmaterias`, `alumnos_idalumnos`),
  INDEX `fk_evaluacion_tc_materias1_idx` (`materias_idmaterias`),
  INDEX `fk_evaluacion_tc_alumnos1_idx` (`alumnos_idalumnos`),
  CONSTRAINT `fk_evaluacion_tc_materias1`
    FOREIGN KEY (`materias_idmaterias`)
    REFERENCES `materias` (`idmaterias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evaluacion_tc_alumnos1`
    FOREIGN KEY (`alumnos_idalumnos`)
    REFERENCES `alumnos` (`idalumnos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evaluacion_e`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evaluacion_e` (
  `idevaluacion_e` INT NOT NULL AUTO_INCREMENT,
  `parcial1` DECIMAL(2,2) NULL,
  `parcial2` DECIMAL(2,2) NULL,
  `parcial3` DECIMAL(2,2) NULL,
  `asistencia1` INT NULL,
  `asistencia2` INT NULL,
  `asistencia3` INT NULL,
  `submodulos_idsubmodulos` INT NOT NULL,
  `alumnos_idalumnos` INT NOT NULL,
  PRIMARY KEY (`idevaluacion_e`, `submodulos_idsubmodulos`, `alumnos_idalumnos`),
  INDEX `fk_evaluacion_e_submodulos1_idx` (`submodulos_idsubmodulos`),
  INDEX `fk_evaluacion_e_alumnos1_idx` (`alumnos_idalumnos`),
  CONSTRAINT `fk_evaluacion_e_submodulos1`
    FOREIGN KEY (`submodulos_idsubmodulos`)
    REFERENCES `submodulos` (`idsubmodulos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evaluacion_e_alumnos1`
    FOREIGN KEY (`alumnos_idalumnos`)
    REFERENCES `alumnos` (`idalumnos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

--
-- Estructura de tabla para la tabla `avisos`
--

CREATE TABLE IF NOT EXISTS `avisos` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `titulo` varchar(255) NOT NULL,
  `descripcion` text DEFAULT NULL,
  `fecha` date DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `concursos`
--

CREATE TABLE IF NOT EXISTS `concursos` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `titulo` varchar(255) NOT NULL,
  `descripcion` text DEFAULT NULL,
  `url_imagen` varchar(255) DEFAULT NULL,
  `fecha` date DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `noticias`
--

CREATE TABLE IF NOT EXISTS `noticias` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `titulo` varchar(45) NOT NULL,
  `descripcion` varchar(255) NOT NULL,
  `img` varchar(255) DEFAULT NULL,
  `fecha` date DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
